CREATE DATABASE DEMO;

use DEMO;

DROP TABLE T_PATIENT;

CREATE TABLE T_PATIENT
( 
  F_PATIENT_NAME VARCHAR(100),
  F_PATIENT_ID BIGINT,
  F_CREATED_TIMESTAMP DATETIME,
  F_AGE BIGINT,
  F_TXN_ID BIGINT,
  F_GENDER VARCHAR(100),
  F_CREATED_BY VARCHAR(100),
  F_DOWNLOAD_PATH     varchar(1000),
  F_AADHAR_NO         varchar(15),
  F_UPDATED_TIMESTAMP date   
);

DROP TABLE T_CLINIC_DETAILS;

CREATE TABLE T_CLINIC_DETAILS
(   
  F_CLINIC_OWNER_NAME VARCHAR(100),
  F_TYPE     VARCHAR(500),
  F_ADDRESS   VARCHAR(1000),
  F_DISTRICT  VARCHAR(50),
  F_STATE     VARCHAR(40),
  F_PINCODE       BIGINT,
  F_CONTACT_NO    BIGINT,
  F_CLINIC_NAME VARCHAR(500),
  F_PATIENT_ID BIGINT
);

DROP TABLE T_FORM;

CREATE TABLE T_FORM
(
	  F_NO_OF_CHILDREN INT,
	  F_GUARDIAN_NAME VARCHAR(300),
	  F_PATIENT_ADDRESS VARCHAR(400),
	  F_REFERRAL_ADDRESS VARCHAR(400),
	  F_MENSTRUAL_PERIOD INT,
	  F_MEDICAL_DISEASE VARCHAR(400),
	  F_PARENTAL_DIAGNOSIS VARCHAR(400),
	  F_GYNA_DETAILS VARCHAR(500),
	  F_CREATED_TIMESTAMP DATE,
	  F_NO_OF_MALE_KIDS INT,
	  F_NO_OF_FEMALE_KIDS INT,
	  F_ADDRESS_ID BIGINT,
	  F_INVASIVE_ID BIGINT,
	  F_NON_INVASIVE_ID BIGINT,
	  F_CLINIC_ID BIGINT,
	  F_PATIENT_ID BIGINT
  );

DROP TABLE T_NON_INVASIVE_PROCEDURES;

CREATE TABLE T_NON_INVASIVE_PROCEDURES
  (
   F_NON_INVASIVE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
   F_FORM_ID BIGINT,
   F_PATIENT_ID BIGINT,
   F_DOCTOR_NAME VARCHAR(100),
   F_DIAGNOSIS_INDICATION varchar(200),
   F_CARRIED_NON_INVASIVE_PROCEDURE  VARCHAR(200),
   F_DECLARATION_DATE   DATE,
   F_PROCEDURE_CARRIED_DATE DATE,
   F_PROCEDURE_RESULT VARCHAR(100),
   F_CONVEY_ID BIGINT,
   F_MTP_INDICATION VARCHAR(100),
   F_DATE DATE,
   F_PLACE VARCHAR(100),
   F_SELECTED_DIAGNOSE  varchar(500)
  );

DROP TABLE T_INVASIVE_PROCEDURES;

CREATE
  TABLE T_INVASIVE_PROCEDURES
  (
    F_INVASIVE_ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    F_FORM_ID                    BIGINT,
    F_PATIENT_ID                 BIGINT,
    F_DOCTOR_NAME                VARCHAR(100),
    F_DIAGNOSIS_BASICS           VARCHAR(200),
    F_DIAGNOSIS_INDICATION       VARCHAR(200),
    F_ADVANCED_MATERNAL_AGE      VARCHAR(100),
    F_GENETIC_DISEASE            VARCHAR(200),
    F_CONTEST_DATE               DATE,
    F_CARRIED_INVASIVE_PROCEDURE VARCHAR(200),
    F_COMPILICATION              VARCHAR(500),
    F_ADDITIONAL_TEST            VARCHAR(1000),
    F_PROCEDURE_RESULT           VARCHAR(100),
    F_PROCEDURE_CARRIED_DATE     DATE,
    F_MTP_INDICATION             VARCHAR(100)
  );
  
DROP TABLE T_CONVEY_DETAILS;
  
CREATE TABLE T_CONVEY_DETAILS
( 
  F_CONVEY_ID INT AUTO_INCREMENT PRIMARY KEY,
  F_PATIENT_ID INT,  
  F_CONVEY_NAME VARCHAR(100),
  F_CONVEY_DATE DATE
);

DROP TABLE T_DOCTOR_DECLARATION;

CREATE TABLE T_DOCTOR_DECLARATION
( 
  F_DECLARATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  F_PATIENT_ID BIGINT,
  F_PATIENT_NAME   varchar(500),
  F_DOCTOR_NAME VARCHAR(100),
  F_DATE DATE,
  F_PLACE VARCHAR(100)
);

DROP TABLE T_PATIENT_ADDRESS;

CREATE TABLE T_PATIENT_ADDRESS
(
	F_DISTRICT        VARCHAR(50),
	F_STATE           VARCHAR(40),
	F_PINCODE         BIGINT,
	F_CONTACT_NO      BIGINT,
	F_ADDRESS_ID      BIGINT,
	F_ADDRESS         VARCHAR(1000),
	F_PATIENT_ID      BIGINT,
	F_CITY            VARCHAR(50)
);

DROP TABLE T_PATIENT_CURRENT_ADDRESS;

CREATE TABLE T_PATIENT_CURRENT_ADDRESS
(
	F_DISTRICT_CURRENT        VARCHAR(50),
	F_STATE_CURRENT           VARCHAR(40),
	F_PINCODE_CURRENT         BIGINT(11),
	F_CONTACT_NO_CURRENT      BIGINT(11),
	F_ADDRESS_ID      BIGINT(11),
	F_ADDRESS_CURRENT         VARCHAR(1000),
	F_PATIENT_ID      BIGINT(11),
	F_CITY_CURRENT            VARCHAR(50),
	F_SAME_AS_PRESENT_ADDRESS VARCHAR(5)
);

DROP TABLE T_REFERRAL_ADDRESS;

CREATE TABLE T_REFERRAL_ADDRESS
  (
    f_patient_id    BIGINT PRIMARY KEY,
    f_referral_name VARCHAR(100),
	F_REFERRAL_ADDRESS_ID BIGINT,
    f_address       VARCHAR(1000),
    f_district      VARCHAR(50),
    f_state         VARCHAR(40),
    f_pincode       BIGINT,
    f_contact_no    BIGINT
  ); 
  
---------------- User tables-------------------
DROP TABLE T_USER_DETAILS;

CREATE TABLE T_USER_DETAILS
  (
    F_LOGIN_ID      VARCHAR(20) NOT NULL PRIMARY KEY,
    F_PASSWORD      VARCHAR(50) NOT NULL,
    F_IS_ENABLED    VARCHAR(20),
    F_MOBILE_NUMBER VARCHAR(11),
    F_DISPLAY_NAME  VARCHAR(20),
    F_CREATED_BY    VARCHAR(20),
    F_CREATION_DATE DATE
  );

DROP TABLE T_USER_ADDRESS;

CREATE
  TABLE T_USER_ADDRESS
  (
    F_LOGIN_ID VARCHAR(20),
    F_DISTRICT VARCHAR(50),
    F_STATE    VARCHAR(30)
  );

DROP TABLE T_USER_ROLES;

CREATE TABLE T_USER_ROLES
  (
    F_LOGIN_ID VARCHAR(20),
    F_ROLE     VARCHAR(30)
  );

INSERT
INTO
  T_USER_DETAILS
  (
    F_LOGIN_ID,
    F_PASSWORD,
    F_IS_ENABLED,
    F_DISPLAY_NAME,
    F_MOBILE_NUMBER,
    F_CREATED_BY,
    F_CREATION_DATE
  )
  VALUES
  (
    'Administrator',
    'd16c36ef27272d2df565632f8595504f',
    'true',
    'Administrator',
    '9849440930',
    'Superuser',
    sysdate()
  );

INSERT
INTO
  T_USER_ADDRESS
  (
    F_LOGIN_ID,
    F_DISTRICT,
    F_STATE
  )
  VALUES
  (
    'Administrator',
    'WARANGAL',
    'TELANGANA'
  );

INSERT
INTO
  T_USER_ROLES
  (
    F_LOGIN_ID,
    F_ROLE
  )
  VALUES
  (
    'Administrator',
    'Administrator'
  );

INSERT
INTO
  T_USER_DETAILS
  (
    F_LOGIN_ID,
    F_PASSWORD,
    F_IS_ENABLED,
    F_DISPLAY_NAME,
    F_MOBILE_NUMBER,
    F_CREATED_BY,
    F_CREATION_DATE
  )
  VALUES
  (
    'sekhar',
    '202cb962ac59075b964b07152d234b70',
    'true',
    'BabuSek',
    '8978399338',
    'Superuser',
    sysdate()
  );

INSERT
INTO
  T_USER_ADDRESS
  (
    F_LOGIN_ID,
    F_DISTRICT,
    F_STATE
  )
  VALUES
  (
    'sekhar',
    'WARANGAL',
    'TELANGANA'
  );

INSERT
INTO
  T_USER_ROLES
  (
    F_LOGIN_ID,
    F_ROLE
  )
  VALUES
  (
    'sekhar',
    'Administrator'
  );

COMMIT;
